### ISSUE TITLE
Unable to downoad necessary files to install

### ISSUE THREAD

**Issue by TheRogueZeta** [ArminJo/DigistumpArduino#12]
I have added the URL to the additional boards config (Arduino 1.8.13) but when I attempt to update or install I see the following error:

![image](https://user-images.githubusercontent.com/1578743/107598920-e89ff280-6bd3-11eb-8b62-0b4a21adda24.png)

I can manually follow the link to http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip and download it.

If I manually download it, where do I place it?

**Comment by ArminJo** [comment]
Please post the error message, you see in the Arduino output window, below the sketch editor.

**Comment by TheRogueZeta** [comment]
```
Error downloading http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:175)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Error downloading http://downloads.arduino.cc/tools/avr-gcc-7.3.0-atmel3.6.1-arduino5-i686-w64-mingw32.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:149)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:83)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:60)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:113)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onInstallPressed$2(ContributionManagerUI.java:172)
	... 1 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3444)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3437)
	at cc.arduino.utils.network.FileDownloader.readStreamCopyTo(FileDownloader.java:268)
	at cc.arduino.utils.network.FileDownloader.openConnectionAndFillTheFile(FileDownloader.java:247)
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:182)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:129)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:147)
	... 5 more
```

**Comment by ArminJo** [comment]
Thanks for reorting, but it works for me, so it looks like your internet is broken.

**Comment by TheRogueZeta** [comment]
I'd like to respectfully disagree as it downloads the first portion just fine from the link and I am able to download it from a web browser just fine and I am able to use the same PC to update this issue.

**Comment by ArminJo** [comment]
Ok you are right, but I can not look inside your head or on your desktop.
So what is the problem? Is your Arduino installation broken?
Or do you think I delivered a virus, which is able to force `java.net.SocketException: Connection reset` on user PC's?
